# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 13:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiklaguser',
            name='first_name',
            field=models.CharField(default=0, max_length=70, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiklaguser',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiklaguser',
            name='last_name',
            field=models.CharField(default=1, max_length=70, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiklaguser',
            name='location',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiklaguser',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
